apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.27.0.7:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    url: http://172.27.0.2:3100
    editable: true
    jsonData:
      maxLines: 1000

  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://172.27.0.4:9411
    editable: true

